# Generated by Django 6.0 on 2026-01-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatDiagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_anak', models.CharField(max_length=100)),
                ('usia', models.CharField(max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('hasil', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekomendasi', to='expert.domainperkembangan')),
            ],
        ),
    ]
