# Generated by Django 6.0 on 2026-01-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_riwayatdiagnosa_rekomendasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kegiatan', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
