# Generated by Django 6.0 on 2026-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_galerikegiatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('handphone', models.CharField(blank=True, max_length=20, null=True)),
                ('pesan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
